# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger: none

pool:
  vmImage: 'macos-latest'

steps:

- task: Xcode@5
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/HealthDataSync.xcworkspace'
    scheme: 'HealthDataSync_Tests'
    xcodeVersion: '11'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'
